= My Project
firstname lastname
1.1.0, yyyy-mm-dd: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/asciidoctor-docker-template/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/Dumfarth-Felix/Rocketman-ProjektAuftrag] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Project Proposal
=== Project name
Rocketman

=== Pre-project
There has been build a Rocket for the CanSat Competition that need a mobile launch suitcase.

=== Assignment of tasks
Our assigment of task is that we build and code a suitcase that can start a rocket wireless.


=== Goal
* With the mobile control unit it should be possible on the one hand to ignite model rockets by cable and on the other hand to carry out wireless communication (control and reception of telemetry data) with several branch offices at the same time. Communication should take place in two frequency ranges or with two protocols at the same time (433 MHz LoRa and 802.11b / g / n network using XBee 568).
* It's not a goal to build the rocket just the suitcase.

|===
|phase |milestone

|components
|get all the componets we need

|building
|assemble all the different components

|connect hardware and software
|code the interface for all the different hardware

|rocket
|code the communication to the rocket

| UI
| code the User Interface and touch compatibility

|===


== Project start
After our yet to be meeting with DJ Ernecker

== Project End
When we get our Diploma or when we are done



